server:
  port: 9991
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: y123qwer1
    url: jdbc:mysql://120.48.61.75:3306/OjBase?serverTimezone=GMT%2B8
  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    port: 25
    username: 1317332365@qq.com
    password: jmyvczfjvwbcidie
  redis:
    host: 120.48.61.75
    port: 6379
    password: yh123456
    lettuce:
      pool:
        max-active: 32
        max-idle: 8
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      id-type: auto
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl